recycle/urls.py
from django.urls import path
from . import views

app_name = 'recycle-logs'

urlpatterns = [
    path('new/', views.log_recycle, name='log-recycle'),
    path('view-logs/', views.view_recycle_logs, name='view-logs'),
]

wms/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage),
    path("users/", include("users.urls")),
    path("schedules/", include("schedule.urls")),
    path("recycle-logs/", include("recycle.urls")),
    path('reports/', include("reports.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

recycle/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Recycle(models.Model):
    RECYCLABLES =[
        ('plastic','Plastic'),
        ('glass','Glass'),
        ('metal','Metal'),
        ('paper','Paper')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=20, choices=RECYCLABLES)
    quantity = models.FloatField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.type} - {self.quantity}kg - {self.date}"

    def formatted_date(self):
        return self.date.strftime("%B %d, %Y, %I:%M %p")

recycle/forms.py
from django import forms

from .models import Recycle


class RecycleForm(forms.ModelForm):
    class Meta:
        model = Recycle
        fields =['type','quantity']

recycle/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from recycle.forms import RecycleForm
from recycle.models import Recycle

# Create your views here.
@csrf_exempt
def log_recycle(request):
    if request.method == 'POST':
        form = RecycleForm(request.POST)
        if form.is_valid():
            recycle = form.save(commit=False)
            recycle.user = request.user
            recycle.save()
            return redirect('recycle-logs:view-logs')
    else:
        form = RecycleForm()
    return render(request, 'log-recycle.html', {'form': form})

def view_recycle_logs(request):
    logs = Recycle.objects.all().order_by('id')

    # Paginate logs, showing 30 logs per page
    paginator = Paginator(logs, 100)  # Show 30 logs per page
    page_number = request.GET.get('page')  # Get the page number from the query parameters
    page_obj = paginator.get_page(page_number)

    return render(request, 'view-logs.html', {'logs': page_obj})

recycle/templates/log-recycle.html
{% extends 'layout.html' %} {% block title %}Log Recycling{% endblock %} {%
block content %}
<div class="flex-1 flex items-center justify-center flex-col p-4">
   <h1 class="text-4xl font-bold text-green-600 my-4">
      Log Your Recycling Activity
   </h1>
   <form
      method="post"
      class="shadow-xl shadow-green-600 my-4 p-8 rounded-lg w-1/2"
   >
      {# {% csrf_token %}#}
      <div class="mb-4">
         <label for="id_type" class="block text-gray-700 font-bold mb-2"
            >Recyclable Type:</label
         >
         <select
            id="id_type"
            name="type"
            class="border border-gray-300 rounded p-4 w-full"
            {{
            form.type
            |
            safe
            }}
         >
            {% for value, label in form.type.choices %}
            <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
         </select>
      </div>
      <div class="mb-4">
         <label for="id_quantity" class="block text-gray-700 font-bold mb-2"
            >Quantity:</label
         >
         <input
            type="text"
            id="id_quantity"
            name="quantity"
            class="border border-gray-300 rounded p-4 w-full"
            {{
            form.quantity.as_p
            |
            safe
            }}
         />
      </div>
      <button
         type="submit"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
      >
         Log Recycling
      </button>
   </form>
</div>
{% endblock %}

recycle/templates/view-logs.html
{% extends 'layout.html' %} {% load static %} {% block title %}View Recycling
Activities{% endblock %} {% block content %}
<div class="p-4 flex flex-col items-center">
   <h1 class="text-green-600 font-bold text-4xl">Your Recycling Activities</h1>
   <ul class="flex gap-4 my-4 flex-wrap items-center justify-center">
      {% for log in logs %}
      <li class="shadow-lg shadow-green-600 p-4 rounded-lg text-xl">
         {% if log.type == "plastic" %}
         <img
            src="{% static 'media/plastic.jpeg' %}"
            alt="Plastic"
            class="h-36 w-96 rounded-lg object-cover"
         />
         {% elif log.type == "glass" %}
         <img
            src="{% static 'media/glass.jpeg' %}"
            alt="Glass"
            class="h-36 w-96 rounded-lg object-cover"
         />
         {% elif log.type == "metal" %}
         <img
            src="{% static 'media/metal.jpeg' %}"
            alt="Metal"
            class="h-36 w-96 rounded-lg object-cover"
         />
         {% elif log.type == "paper" %}
         <img
            src="{% static 'media/paper.jpeg' %}"
            alt="Paper"
            class="h-36 w-96 rounded-lg object-cover"
         />
         {% endif %}
         <p class="text-2xl mt-2">
            Type: <span class="font-bold text-green-600">{{ log.type }}</span>
         </p>
         <p class="text-2xl mt-2">
            Quantity:
            <span class="font-bold text-green-600">{{ log.quantity }}kg</span>
         </p>
         <p class="text-2xl mt-2">
            On: <span class="font-bold text-green-600">{{ log.date }}</span>
         </p>
      </li>
      {% endfor %}
   </ul>

   <!-- Pagination Controls -->
   <div
      class="my-8 text-xl border-4 rounded-md border-green-600 px-6 py-12 w-2/4 text-center"
   >
      {% if logs.has_previous %}
      <a
         href="?page=1"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
         >&laquo; First</a
      >
      <a
         href="?page={{ logs.previous_page_number }}"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
         >Previous</a
      >
      {% endif %}

      <span class="page-info"
         >Page {{ logs.number }} of {{ logs.paginator.num_pages }}</span
      >

      {% if logs.has_next %}
      <a
         href="?page={{ logs.next_page_number }}"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
         >Next</a
      >
      <a
         href="?page={{ logs.paginator.num_pages }}"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
         >Last &raquo;</a
      >
      {% endif %}
   </div>
</div>
{% endblock %}