schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedules'

urlpatterns = [
    path('new/', views.create_schedule, name='create-schedule'),
    path('all/', views.view_schedules, name='view-schedules'),
]

wms/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage),
    path("users/", include("users.urls")),
    path("schedules/", include("schedule.urls")),
    path("recycle-logs/", include("recycle.urls")),
    path('reports/', include("reports.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

schedule/models.py
from django.db import models
from django.contrib.auth.models import User

class Schedule(models.Model):
    dayS = [
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday'),
    ]

    FREQUENCIES = [
        ('Weekly', 'Weekly'),
        ('Monthly', 'Monthly'),
    ]

    day = models.CharField(max_length=10, choices=dayS)
    time = models.TimeField()
    frequency = models.CharField(max_length=10, choices=FREQUENCIES)

    def __str__(self):
        return f"{self.day} - {self.time} - {self.frequency}"

schedule/forms.py
from django import forms

from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['day', 'time', 'frequency']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['day'].choices = Schedule.dayS
        self.fields['frequency'].choices = Schedule.FREQUENCIES

schedule/views.py
from django.views.decorators.csrf import csrf_exempt

from schedule.models import Schedule
from schedule.forms import ScheduleForm
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

# Create your views here.
@csrf_exempt
def create_schedule(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            schedule = form.save(commit=False)
            schedule.save()
            return redirect('schedules:view-schedules')
    else:
        form = ScheduleForm()
    return render(request, 'create-schedule.html', {'form': form})

def view_schedules(request):
    schedules = Schedule.objects.all().order_by('id')

    # Set up pagination (30 schedules per page)
    paginator = Paginator(schedules, 100)  # Show 30 schedules per page

    # Get the page number from the request query parameters
    page_number = request.GET.get('page')

    # Get the corresponding page of schedules
    page_schedules = paginator.get_page(page_number)

    # Pass the paginated schedules to the template
    return render(request, 'view-schedules.html', {'schedules': page_schedules})

schedule/templates/create-schedule.html
{% extends 'layout.html' %} {% block title %} Create your schedule {% endblock
%} {% block content %}
<div class="flex-1 flex items-center justify-center flex-col p-4">
   <h1 class="text-4xl font-bold text-green-600 my-4">Create your schedule</h1>
   <form method="post" class="w-1/2">
      {# {% csrf_token %}#}
      <div class="mb-4">
         <label for="id_day" class="block text-gray-700 font-bold mb-2"
            >Week day:</label
         >
         <select
            id="id_day"
            name="day"
            class="border border-gray-300 rounded p-4 w-full"
            {{
            form.day
            |
            safe
            }}
         >
            {% for value, label in form.day.choices %}
            <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
         </select>
      </div>
      <div class="mb-4">
         w
         <label for="id_time" class="block text-gray-700 font-bold mb-2"
            >Day time:</label
         >
         <input
            type="text"
            id="id_time"
            name="time"
            class="border border-gray-300 rounded p-4 w-full"
            {{
            form.time.as_p
            |
            safe
            }}
         />
      </div>
      <div class="mb-4">
         <label for="id_frequency" class="block text-gray-700 font-bold mb-2"
            >Frequency</label
         >
         <select
            id="id_frequency"
            name="frequency"
            class="border border-gray-300 rounded p-4 w-full"
            {{
            form.frequency
            |
            safe
            }}
         >
            {% for value, label in form.frequency.choices %}
            <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
         </select>
      </div>
      <button
         type="submit"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
      >
         Save schedule
      </button>
   </form>
</div>
{% endblock %}

schedule/templates/view-schedules.html
{% extends 'layout.html' %}
{% block title %} Your schedules {% endblock %}
{%block content %}
<div class="p-8 flex flex-col items-center justify-center">
   <h1 class="text-green-600 font-bold text-4xl my-4">Your schedules</h1>
   <ul class="flex gap-8 my-4 flex-wrap items-center justify-center">
      {% for schedule in schedules %}
      <li class="shadow-lg shadow-green-600 py-8 px-16 rounded-lg text-2xl">
         <div class="flex items-start gap-2">
            <p class="schedule-day">Date:</p>
            <span class="text-green-600 font-bold">{{ schedule.day }}</span>
         </div>
         <div class="flex items-center gap-2">
            <p class="schedule-time">Time:</p>
            <span class="text-green-600 font-bold">{{ schedule.time }}</span>
         </div>
         <div class="flex items-center gap-2">
            <p class="schedule-frequency">Schedule:</p>
            <span class="text-green-600 font-bold">{{ schedule.frequency }}</span>
         </div>
      </li>
      {% endfor %}
   </ul>

   <!-- Pagination controls -->
   <div
      class="my-8 text-xl border-4 rounded-md border-green-600 px-6 py-12 w-2/4 text-center"
   >
      {% if schedules.has_previous %}
      <a
         href="?page=1"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
         >&laquo; First</a>
      <a
         href="?page={{ schedules.previous_page_number }}"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
         >Previous</a
      >
      {% endif %}

      <span class="page-info">Page {{ schedules.number }} of {{ schedules.paginator.num_pages}}</span>
      {% if schedules.has_next %}
      <a
         href="?page={{ schedules.next_page_number }}"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
      >Next</a>
      <a
         href="?page={{ schedules.paginator.num_pages }}"
         class="p-4 rounded-md bg-green-600 text-white w-full my-1 transition-all duration-300 hover:bg-green-400"
      >Last &raquo;</a>
      {% endif %}
   </div>
</div>
{% endblock %}