recycle/urls.py
from django.urls import path
from . import views

app_name = 'recycle-logs'

urlpatterns = [
    path('new/', views.log_recycle, name='log-recycle'),
    path('view-logs/', views.view_recycle_logs, name='view-logs'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns =[
    path('new/', views.generate_report, name='generate-report'),
    path('all/', views.view_reports, name='view-reports'),
]

schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedules'

urlpatterns = [
    path('new/', views.create_schedule, name='create-schedule'),
    path('all/', views.view_schedules, name='view-schedules'),
]

users/urls.py
from . import views
from django.urls import path

app_name = 'users'

urlpatterns =[
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('check/', views.check_user_exists, name='check_user_exists'),
    path('/', views.list_users, name='list-users'),
]

wms/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.homepage),
    path("users/", include("users.urls")),
    path("schedules/", include("schedule.urls")),
    path("recycle-logs/", include("recycle.urls")),
    path('reports/', include("reports.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

templates/auth.html
<!DOCTYPE html>
{% load custom_filters %}
{% load static tailwind_tags %}
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        {% tailwind_css %}
        <link rel="icon" type="image/x-icon" href="{% static 'media/favicon.ico' %}">
    </head>
    <body>
    <main class="w-screen max-h-screen flex items-center justify-center flex-1">
        <div class="w-1/2">
            <img alt="auth-image" src="{% static 'media/auth-image.jpeg' %}"/>
        </div>
        <div class="w-1/2 flex items-center justify-center p-4">
            {% block content %}{% endblock %}
        </div>
    </main>
    </body>
</html>

templates/index.html
{% extends 'layout.html' %}
{% load custom_filters %}
{% load static %}
{% block title %} Welcome {% endblock %}
{% block content %}
    <div class="flex-1">
        {% if user.is_authenticated %}
        	<h3 class="text-5xl block text-center my-4 text-green-600">Welcome {{ user.username|remove_email_domain|title }}</h3>
        {% else %}
            <h3 class="text-5xl block text-center my-4 text-green-600">Welcome to the <span>Waste Management system</span></h3>
        {% endif %} 
         <p class="text-center text-2xl">
             Our system helps you manage waste collection schedules,<br/>
             track recycling activities, and generate detailed reports. Here's what you can do:
         </p>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4 p-8">
            <div class="shadow-lg shadow-green-600 p-4 rounded-lg">
                <img class="w-full rounded-md" src="{% static 'media/schedule.jpeg' %}" alt="Schedule">
                <h2 class="mt-4 text-green-600 font-bold text-3xl">Manage Waste Collection Schedules</h2>
                <p>Easily set and view your waste collection schedules to ensure timely pickups.</p>
            </div>
            <div class="shadow-lg shadow-green-600 p-4 rounded-lg">
                <img class="w-full rounded-md" src="{% static 'media/recycling.jpeg' %}" alt="Recycle">
                <h2 class="mt-4 text-green-600 font-bold text-3xl">Track Recycling Activities</h2>
                <p>Keep track of your recycling efforts with detailed logs and records.</p>
            </div>
            <div class="shadow-lg shadow-green-600 p-4 rounded-lg">
                <img class="w-full rounded-md" src="{% static 'media/reports.jpeg' %}" alt="Report">
                <h2 class="mt-4 text-green-600 font-bold text-3xl">Generate Reports</h2>
                <p>Generate comprehensive reports to monitor and improve your waste management practices.</p>
            </div>
        </div>
        {% if not user.is_authenticated %}
        	 <div class="flex items-center justify-center flex-col mb-20">
                <h2 class="text-green-600 text-4xl my-4">Get Started Today!</h2>
                <div class="flex gap-1 w-2/4">
                    <a
                            href="{% url 'users:register' %}"
                            class="px-6 py-4 rounded-md bg-green-600 text-white w-full my-1 text-center transition-all duration-300 hover:bg-white hover:text-green-600 hover:border-2 hover:border-green-600 hover:rounded-md"
                    >
                        Register now
                    </a>
                    <a
                            href="{% url 'users:login' %}"
                            class="px-6 py-4 rounded-md bg-emerald-600 text-white w-full my-1 text-center transition-all duration-300 hover:bg-white hover:border-2 hover:text-emerald-600 hover:border-emerald-600 hover:rounded-md"
                    >
                        Login here
                    </a>
                </div>
            </div>
        {% endif %} 
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load custom_filters %}
{% load static tailwind_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>{% block title %}Waste Management System{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% tailwind_css %}
    <link rel="icon" type="image/x-icon" href="{% static 'media/favicon.ico' %}">
</head>
<body class="w-full h-screen">
    <header class="w-full static top-0 left-0 z-50 px-16 py-2 bg-green-600 text-white flex items-center justify-between">
        <a href="/" class="no-underline">
            <img alt="logo" src="{% static 'media/logo.png' %}" class="size-20"/>
        </a>
        <nav class="links">
             <a
                     href="{% url 'schedules:create-schedule' %}"
                     title="Create schedule"
                     class="text-xl ml-2 transition-all duration-300 hover:underline"
             >
                Schedule
            </a>
            <a
                    href="{% url 'schedules:view-schedules' %}"
                    title="Schedules"
                    class="text-xl ml-2 transition-all duration-300 hover:underline"
            >
                Schedules
            </a>
            <a
                    href="{% url 'reports:generate-report' %}"
                    title="Generate report"
                    class="text-xl ml-2 transition-all duration-300 hover:underline"
            >
                Report
            </a>
           <a
                   href="{% url 'reports:view-reports' %}"
                   title="Your reports"
                   class="text-xl ml-2 transition-all duration-300 hover:underline"
           >
                Reports
            </a>
            <a
                href="{% url 'recycle-logs:log-recycle' %}"
                title="Create recycling schedule"
                class="text-xl ml-2 transition-all duration-300 hover:underline"
            >
                Recycle
            </a>
             <a
                     href="{% url 'recycle-logs:view-logs' %}"
                     title="View logs"
                     class="text-xl ml-2 transition-all duration-300 hover:underline"
             >
                Recycles
            </a>
        </nav>
        <div class="user">
            {% if user.is_authenticated %}
               <div class="flex text-xl gap-2 items-center">
                    <p>Hi, {{ user.username|remove_email_domain|title }}</p>
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="bg-white transition duration-300 hover:scale-110 text-green-600 px-2 py-1 rounded-md">Logout</button>
                    </form>
               </div>
            {% else %}
                <div class="flex text-xl gap-4">
                    <a href="{% url 'users:login' %}" title="Login user" class="transition-all duration-300 hover:underline">Login</a>
                    <a href="{% url 'users:register' %}" title="Register user" class="transition-all duration-300 hover:underline">Register</a>
                </div>
            {% endif %}
        </div>
    </header>
    <main class="flex flex-col">
         {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endfor %}
                </div>
         {% endif %}
         {% block content %}{% endblock %}
    </main>
     <script>
        document.addEventListener('DOMContentLoaded', function () {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(alert => {
                setTimeout(() => {
                    alert.classList.add('fade-out');
                }, 5000);
            });
        });
    </script>
</body>
</html>